version: '3'
services:
  cassandra-node-1:
    image: custom-cassandra-image:3.7
    container_name: cassandra-node-1
    ports:
      - "9046:9042"
    networks:
      - cassandra-net

  cassandra-node-2:
    image: custom-cassandra-image:3.7
    container_name: cassandra-node-2
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1
    ports:
      - "9047:9042"
    networks:
      - cassandra-net

  cassandra-node-3:
    image: custom-cassandra-image:3.7
    container_name: cassandra-node-3
    environment:
      - CASSANDRA_SEEDS=cassandra-node-1,cassandra-node-2
    ports:
      - "9048:9042"
    networks:
      - cassandra-cluster-network

networks:
  cassandra-cluster-network: